# Numpy arrays vs Lists 

In [5]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

1.7085316181182861


In [6]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.15777039527893066


# Advanced Indexing 

In [9]:
# Normal Indexing and Slicing 
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

### Fancy Indexing 

In [24]:
a
a[[0,2,3]] 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

* If we wanted 1st and 3rd row we could get it using slicing but in case we want 1st , 3rd and 4th row there is no pattern here in this case we need to use fancy indexing
* In case of fancy indexing we just pass whatever rows we need in the form of a list  

# Boolean Indexing



In [29]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[92,  6, 88, 17],
       [33, 78, 90, 28],
       [81, 81, 45,  1],
       [14,  6, 21, 37],
       [86,  1, 11, 31],
       [39, 34, 71, 72]])

#### filtering using boolean indexing

In [45]:
# find all the numbers greater than 60
a>50
a[a>50] # filtering data by using the boolean array as a mask

array([[ True, False,  True, False],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False,  True,  True]])

array([92, 88, 78, 90, 81, 81, 86, 71, 72])

In [46]:
# find out even numbers 
a[a%2==0]

array([92,  6, 88, 78, 90, 28, 14,  6, 86, 34, 72])

In [47]:
# find all numbers that are greater than 50 and also even
a[(a>50) & (a%2==0)]

array([92, 88, 78, 90, 86, 72])

In [55]:
# find all numbers that are not divisible by 7
a[~(a%7==0)].size(

array([92,  6, 88, 17, 33, 78, 90, 81, 81, 45,  1,  6, 37, 86,  1, 11, 31,
       39, 34, 71, 72])