In [5]:
import numpy as np 

In [7]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
type(arr)

numpy.ndarray

### Creating specific types of arrays in numpy 

In [13]:
arr_float = np.array([1.4,2.4,3.2],dtype=float)
arr_float

array([1.4, 2.4, 3.2])

In [26]:
arr_bool = np.array([1,3,4,0],dtype=bool)
arr_bool

array([ True,  True,  True, False])

* **we can give the data type by giving dtype attribute while creating the arrays**  

## 2D Arrays
* **We can call them matrix**

In [17]:
two_dim_array = np.array([[1,2,3],[1,2,3]])
two_dim_array

array([[1, 2, 3],
       [1, 2, 3]])

### Use of arange and reshape 

In [29]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.arange(1,11).reshape(5,2)
# Here we got a 2D matrix with 5 rows and 2 coloumns 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### np.ones

In [51]:
arrOne =np.ones((3,4),dtype=int)
arrTwo =np.ones((3,4)) # This will contain float values 
print(arrOne)
print(arrTwo)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### np.zeros

In [45]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### np.random

In [57]:
np.random.random((3,3))

array([[0.47434842, 0.53242082, 0.53517496],
       [0.46116359, 0.96143648, 0.54951428],
       [0.88258117, 0.37403505, 0.42762385]])

### np.linspace

In [72]:
np.linspace(-10,10,10,dtype=int)
# (start, end , number of points)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

### np.identity

In [70]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])