In [138]:
import numpy as np 

### Creating a array in numpy using a list 

In [140]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [141]:
type(arr)

numpy.ndarray

### Creating specific types of arrays in numpy 

In [143]:
arr_float = np.array([1.4,2.4,3.2],dtype=float)
arr_float

array([1.4, 2.4, 3.2])

In [144]:
arr_bool = np.array([1,3,4,0],dtype=bool)
arr_bool

array([ True,  True,  True, False])

* **we can give the data type by giving dtype attribute while creating the arrays**  

## 2D Arrays
* **We can call them matrix**

In [147]:
two_dim_array = np.array([[1,2,3],[1,2,3]])
two_dim_array

array([[1, 2, 3],
       [1, 2, 3]])

# Different ways to initialize arrays in numpy

### Use of arange and reshape 

In [150]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
np.arange(1,11).reshape(5,2)
# Here we got a 2D matrix with 5 rows and 2 coloumns 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### np.ones

In [153]:
arrOne =np.ones((3,4),dtype=int)
arrTwo =np.ones((3,4)) # This will contain float values 
print(arrOne)
print(arrTwo)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### np.zeros

In [155]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### np.random

In [157]:
np.random.random((3,3))

array([[0.39539499, 0.80544025, 0.58672007],
       [0.92893221, 0.86328225, 0.84985456],
       [0.51766924, 0.97273083, 0.1480494 ]])

### np.linspace

In [159]:
np.linspace(-10,10,10,dtype=int)
# (start, end , number of points)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

### np.identity

In [161]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Some important numpy attributes 

In [163]:
a1 =np.array([[1,2,3],[4,5,6]])
a2 =np.ones((2,3,3))

print(a1)
print(a2)

[[1 2 3]
 [4 5 6]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### ndim : It tells us about the number of dimensions

In [165]:
print(a1.ndim) 
print(a2.ndim)

2
3


### **shape**

In [167]:
print(a1.shape)
print(a2.shape) # Tells us there are 2 ..3x3 matrices 

(2, 3)
(2, 3, 3)


### size -> tells us about the number of elements

In [169]:
# Tells us the number of items present in the array
a1.size 
a2.size

6

18

### itemsize


**int32 takes 4 bytes while int64 takes 8 bytes**

In [172]:
a1.itemsize # int32 = 4
a2.itemsize # float = 8

4

8

In [173]:
array_one = np.array([1,3,4],dtype=np.int32)
array_two = np.array([1,3,4],dtype=np.int64)
array_three = np.array([1,3,4],dtype=float)

array_one.itemsize
array_two.itemsize
array_three.itemsize


4

8

8

# Changing Datatypes

In [175]:
array_four = np.array([1,2,3],dtype=np.int64)
array_four.dtype

dtype('int64')

**astype is used to change the datatype of already made arrays**
* Note -> **`astype()`** method does not change the dtype of the original array in-place; instead, it returns a new array with the specified dtype

In [177]:
array_four_new = array_four.astype(np.int32)
array_four_new.dtype

dtype('int32')

# Array Operations

## Scalar Operations 

**We can use all the mathematical operators here**

In [181]:
a1
a1 *2
a1**2
a1/2
a1>5

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])

array([[ 1,  4,  9],
       [16, 25, 36]])

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

array([[False, False, False],
       [False, False,  True]])

### Vector Operations 


In [183]:
first_arr = np.array([1,2,3])
second_arr = np.array([4,5,6])
first_arr + second_arr
first_arr - second_arr
first_arr * second_arr

array([5, 7, 9])

array([-3, -3, -3])

array([ 4, 10, 18])

### Some important operations 

In [185]:
c1 = np.random.random((3,3))
c1 = np.round(c1*100)
c1

array([[ 3., 81., 23.],
       [74., 47., 57.],
       [25.,  0., 92.]])

**`max` : finds the maximum element in the entire array or in a particular axis**

In [187]:
np.max(c1)
np.max(c1,axis=0) # max from every coloumn
np.max(c1,axis=1) # max from every row 


92.0

array([74., 81., 92.])

array([81., 74., 92.])

**`min` : finds the minimum element in the entire array or in a particular axis**

In [189]:
np.min(c1)

0.0

**`sum`: find the sum of the entire array or a particular axis**

In [191]:
np.sum(c1)
np.sum(c1,axis=1)


402.0

array([107., 178., 117.])

**`prod` :finds the product of an array**

In [193]:
np.prod(c1)

0.0

**we can also find the mean of the entire array or along any axis**

In [195]:
np.mean(c1)
np.mean(c1,axis=0)

44.666666666666664

array([34.        , 42.66666667, 57.33333333])

In [196]:
np.sin(c1) # trigonometric functions 

array([[ 0.14112001, -0.62988799, -0.8462204 ],
       [-0.98514626,  0.12357312,  0.43616476],
       [-0.13235175,  0.        , -0.77946607]])

### Dot Product 

In [198]:
a3 = np.array([1,2,3])
a4 = np.array([4,5,6])
a3.dot(a4)
# 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32

32

In [199]:
# dot product 
a3_ = np.arange(12).reshape(3,4)
a4_ = np.arange(12).reshape(4,3)
a3_
a4_
a3_.dot(a4_)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

**log and exponents**

In [201]:
np.exp(a3) # e^x
np.log(a3) # ln(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229])

**round/floor/ceil**

 `np.round()`:
This function rounds each element of the array to the nearest integer. If the fractional part is 0.5 or greater, the value is rounded up; otherwise, it is rounded down.

In [204]:
arr4 = np.array([1.5, 2.3, 2.5, 3.8])
np.round(arr4) 

array([2., 2., 2., 4.])

 `np.ceil()`:
This function rounds up each element to the nearest integer greater than or equal to the element (essentially truncating towards positive infinity).



In [206]:
arr5 = np.array([1.2, -2.8, 2.3])
np.ceil(arr5) 


array([ 2., -2.,  3.])

 `np.floor()`:
This function rounds down each element to the nearest integer less than or equal to the element (essentially truncating towards negative infinity).

In [208]:
arr6 = np.array([1.7, -2.3, 2.9])
np.floor(arr6)  # Output: array([ 1., -3.,  2.])


array([ 1., -3.,  2.])

# Indexing and Slicing 


**indexing**

In [211]:
v1 = np.arange(10)
m1 = np.arange(12).reshape(3,4)
t1 = np.arange(8).reshape(2,2,2)
v1 , m1 , t1

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [212]:
m1[2,3] # 2nd row and 3rd coloumn

11

In [213]:
t1[0]
t1[0,0]
t1[0,0,1] # 0th matrix ..0 the row ... 1st coloumn

array([[0, 1],
       [2, 3]])

array([0, 1])

1

## Slicing 

`arr[start : end : step]`

In [216]:
v1
v1[2:5]
v1[2::2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2, 3, 4])

array([2, 4, 6, 8])

In [217]:
m1
m1[0,:] # first row and all coloumns
m1[0,1:] # first row and all coloumns from 1 to last 
m1[:,2:3] # all rows and 2 to 3-1 cols
m1[1:,2:3]
m1[::2,::3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([0, 1, 2, 3])

array([1, 2, 3])

array([[ 2],
       [ 6],
       [10]])

array([[ 6],
       [10]])

array([[ 0,  3],
       [ 8, 11]])

In [218]:
t2 = np.arange(27).reshape(3,3,3)
t2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [219]:
t2[1]
t2[::2]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Iterating over numpy arrays 

In [221]:
v1
m1
t1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [269]:
for i in v1:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [275]:

for i in m1:
    print(i,end=" ")


[0 1 2 3] [4 5 6 7] [ 8  9 10 11] 

In [279]:
for i in t1:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


**`np.nditer` : this function converts any dimensional array to single dimensional array and then prints each element**

In [283]:
for i in np.nditer(t1):
    print(i,end=" ")

0 1 2 3 4 5 6 7 

## Transpose and Ravel

In [289]:

m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [297]:
np.transpose(m1)
m1.T # easier syntax

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [307]:
t2
t2.ravel()

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [310]:
a7 = np.array([1,2,3])
a8 = np.array([1,2,3])
a9 = np.arange(12).reshape(3,4)
a10 = np.arange(12,24).reshape(3,4)
a9
a10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**vertical Stacking**

In [315]:
np.hstack((a9,a10))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

**horizontal stacking**

In [318]:
np.vstack((a9,a10))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

--------- v splitting
      |
      |   h splitting 
      |

In [325]:
a11 = np.arange(24).reshape(6,4)
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [327]:
np.hsplit(a11,3)

ValueError: array split does not result in an equal division